import { createCommand } from "#base";
import { ApplicationCommandOptionType, MessageFlags } from "discord.js";
import { linkAccount, authStatusMessage } from "../../minecraft/index.js";

export default createCommand({
  name: "auth",
  description: "Link your Minecraft account to Discord",
  options: [
    {
      name: "code",
      description: "Code generated by /sx auth in Minecraft",
      type: ApplicationCommandOptionType.String,
      required: true,
    },
  ],
  async run(interaction) {
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });
    const code = interaction.options.getString("code", true);

    try {
      const user = interaction.user;
      // Linking is performed by the Java server (the single DB writer) via the typed `auth.link`
      // procedure — the bot never writes the account link itself.
      const result = await linkAccount({
        code,
        discordUserId: user.id,
        discordUsername: user.username,
        discordGlobalName: user.globalName ?? user.username,
        discordAvatar: user.displayAvatarURL({ size: 256, extension: "png" }),
      });
      await interaction.editReply(authStatusMessage(result.status, result.minecraftName));
    } catch (err) {
      console.error("Auth command failed:", err);
      await interaction.editReply(
        "Auth is not available right now. Make sure the Minecraft server is online and the bot's API_TOKEN matches the server's api.token.",
      );
    }
  },
});
