package com.sexidium.core.game.experience;

import com.sexidium.core.platform.model.WorldDimension;
import com.sexidium.core.platform.model.WorldTerrain;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the map-type model: which challenges own a world's terrain, that only ONE of them can ever be
 * active at a time, and that the chosen type survives the trip through the mode args.
 */
class ExperienceWorldTypeTest {

  @Test
  void everyGeneratedMapNamesARealChallenge() {
    for (ExperienceWorldType type : ExperienceWorldType.generatedMaps()) {
      assertTrue(type.generatesMap(), type + " should generate a map");
      assertTrue(ChallengeCatalog.contains(type.challengeId()),
          "unknown challenge for " + type + ": " + type.challengeId());
    }
    for (ExperienceWorldType type : ExperienceWorldType.startDimensions()) {
      assertFalse(type.generatesMap(), type + " is plain terrain");
      assertNull(type.challengeId());
    }
  }

  @Test
  void theVanillaTerrainPresetsAreOrdinaryWorldsOnDifferentTerrain() {
    for (ExperienceWorldType type : ExperienceWorldType.terrainPresets()) {
      // A preset is generated by the game, not built by a challenge: it must add nothing to the grid.
      assertNull(type.challengeId(), type + " must own no challenge");
      assertFalse(type.generatesMap(), type + " does not build a map");
      assertEquals(WorldDimension.OVERWORLD, type.dimension(), type + " starts in the Overworld");
      assertNotEquals(WorldTerrain.NORMAL, type.terrain(), type + " must select a real preset");
      // Terrain is baked in at creation, so a preset can never be applied to an existing world.
      assertTrue(type.fixedAtCreation(), type + " must be fixed at creation");
    }
    assertEquals(List.of(ExperienceWorldType.SUPERFLAT, ExperienceWorldType.LARGE_BIOMES,
        ExperienceWorldType.AMPLIFIED), ExperienceWorldType.terrainPresets());
    assertEquals(WorldTerrain.SUPERFLAT, ExperienceWorldType.SUPERFLAT.terrain());
    assertEquals(WorldTerrain.LARGE_BIOMES, ExperienceWorldType.LARGE_BIOMES.terrain());
    assertEquals(WorldTerrain.AMPLIFIED, ExperienceWorldType.AMPLIFIED.terrain());
  }

  @Test
  void onlyPlainStartDimensionsCanBeChangedAfterCreation() {
    for (ExperienceWorldType type : ExperienceWorldType.startDimensions()) {
      assertEquals(WorldTerrain.NORMAL, type.terrain());
      assertFalse(type.fixedAtCreation(), type + " is only a spawn choice, so it stays re-pointable");
    }
    for (ExperienceWorldType type : ExperienceWorldType.generatedMaps()) {
      assertTrue(type.fixedAtCreation(), type + " builds the world, so it is fixed");
    }
  }

  @Test
  void aTerrainPresetSurvivesTheModeArgsAndAddsNoChallenge() {
    List<String> args = ExperienceWorldType.SUPERFLAT.toModeArgs(List.of("doubledrops"));
    assertEquals(List.of("doubledrops", "world:superflat"), args);
    assertEquals(ExperienceWorldType.SUPERFLAT, ExperienceWorldType.fromArgs(args));
    assertEquals(WorldTerrain.SUPERFLAT, ExperienceWorldType.fromArgs(args).terrain());
    // A preset never smuggles a challenge into the experience the way a generated map does.
    assertEquals(List.of("doubledrops"),
        ExperienceService.challengesFor(List.of("doubledrops"), ExperienceWorldType.AMPLIFIED));
  }

  @Test
  void everyTypeIdRoundTripsThroughOf() {
    for (ExperienceWorldType type : ExperienceWorldType.values()) {
      assertEquals(type, ExperienceWorldType.of(type.id()), "id round-trip for " + type);
      assertEquals(type, ExperienceWorldType.of(type.id().toUpperCase(java.util.Locale.ROOT)));
    }
    assertEquals(ExperienceWorldType.NORMAL, ExperienceWorldType.of("not-a-world"));
  }

  @Test
  void aStoredPresetStillResolvesFromTheStoredIdAlone() {
    // Presets own no challenge, so the challenge list can never re-derive them — the stored id must win.
    assertEquals(ExperienceWorldType.AMPLIFIED,
        ExperienceWorldType.resolve(List.of("doubledrops"), "amplified"));
    assertEquals(ExperienceWorldType.SUPERFLAT, ExperienceWorldType.resolve(List.of(), "superflat"));
    // …but a real map challenge still outranks it (that world genuinely IS a skyblock).
    assertEquals(ExperienceWorldType.RANDOM_LAYERS,
        ExperienceWorldType.resolve(List.of("randomlayers"), "superflat"));
  }

  @Test
  void theSkyblockFamilyIsExactlyTheMapGeneratingSet() {
    assertEquals(java.util.Set.of("classicskyblock", "randomskyblock", "randomlayers", "layereddimensions"),
        ExperienceWorldType.mapChallengeIds());
    // …and those are precisely the challenges kept out of the free-choice grid.
    for (ChallengeCatalog.Entry entry : ChallengeCatalog.selectable()) {
      assertFalse(ChallengeCatalog.isMapChallenge(entry.id()), entry.id() + " must not be selectable");
    }
    assertEquals(ChallengeCatalog.available().size() - 4, ChallengeCatalog.selectable().size());
  }

  @Test
  void mapChallengesReportsEveryGeneratorInARequest() {
    assertEquals(List.of("randomlayers", "classicskyblock"),
        ChallengeCatalog.mapChallenges(List.of("doubledrops", "randomlayers", "cleave", "CLASSICSKYBLOCK")));
    assertEquals(List.of(), ChallengeCatalog.mapChallenges(List.of("doubledrops", "cleave")));
  }

  @Test
  void onlyTheChosenMapSurvivesTheChallengeSet() {
    // Two maps requested at once: the type wins and the other generator is dropped.
    List<String> challenges = ExperienceService.challengesFor(
        List.of("randomlayers", "doubledrops", "classicskyblock"), ExperienceWorldType.RANDOM_SKYBLOCK);
    assertEquals(List.of("randomskyblock", "doubledrops"), challenges);
    // A plain world keeps no generator at all.
    assertEquals(List.of("doubledrops"),
        ExperienceService.challengesFor(List.of("classicskyblock", "doubledrops"), ExperienceWorldType.NETHER));
  }

  @Test
  void theTypeSurvivesTheModeArgsRoundTrip() {
    List<String> args = ExperienceWorldType.NETHER.toModeArgs(List.of("doubledrops"));
    assertEquals(List.of("doubledrops", "world:nether"), args);
    assertEquals(ExperienceWorldType.NETHER, ExperienceWorldType.fromArgs(args));
    assertEquals(List.of("doubledrops"), ExperienceWorldType.stripArgs(args));
    // A generated map contributes its own challenge to the args.
    assertTrue(ExperienceWorldType.CLASSIC_SKYBLOCK.toModeArgs(List.of()).contains("classicskyblock"));
    // No token at all (a legacy match) reads as a normal world.
    assertEquals(ExperienceWorldType.NORMAL, ExperienceWorldType.fromArgs(List.of("doubledrops")));
  }

  @Test
  void aRunningMapChallengeOutranksTheStoredType() {
    // Experiences created before the selector existed carry no stored type — their map still resolves.
    assertEquals(ExperienceWorldType.RANDOM_LAYERS,
        ExperienceWorldType.resolve(List.of("doubledrops", "randomlayers"), null));
    assertEquals(ExperienceWorldType.END, ExperienceWorldType.resolve(List.of("doubledrops"), "end"));
    // A stale generated type whose challenge is gone falls back to a normal world, never a broken map.
    assertEquals(ExperienceWorldType.NORMAL, ExperienceWorldType.resolve(List.of("doubledrops"), "randomlayers"));
    assertEquals(ExperienceWorldType.NORMAL, ExperienceWorldType.resolve(List.of(), "nonsense"));
  }
}
