package com.sexidium.core.menu;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.sexidium.core.menu.MenuArt.Glyph;
import com.sexidium.core.menu.MenuArt.Tile;
import com.sexidium.core.menu.MenuArt.TileRow;

/**
 * The background-tiling half of {@link MenuArt}: the >256px font-atlas workaround that splits a 768px
 * baked background into a {@link MenuArt#TILE_GRID}² grid of ≤256px glyph cells, plus the per-tile
 * advance manifest loader. Computes the per-row strip providers ({@link #tileRows}) the pack emitter
 * needs and the in-reading-order tiles ({@link #tiles}) the title-trick reassembles. Package-private
 * implementation detail of {@link MenuArt}, which exposes the public {@code tiles}/{@code tileRows}
 * facade and the {@code TILE_*} constants.
 */
final class MenuArtTiling {
  /** Classpath resource of per-tile advances generated by {@code scripts/art.py tile-backgrounds}. */
  static final String TILE_ADVANCES_RESOURCE = "/menu/tile-advances.txt";

  // Per-tile horizontal advances (GUI px) for each tiled background, keyed by texture-path stem (e.g.
  // "ui/chest/chest_6"), row-major over the TILE_GRID² grid; 0 = a fully-transparent tile (skipped).
  // Real (content-derived) advances, generated by scripts/art.py tile-backgrounds.
  private static final Map<String, int[]> TILE_ADVANCES = loadTileAdvances();

  private MenuArtTiling() {
  }

  /**
   * The per-row strip providers of a tiled background (top→bottom), for the pack emitter: each is the
   * {@code <stem>.row<r>.png} strip texture, its {@code TILE_GRID} row code points (left→right), and the
   * row's raw font {@code ascent} (= the glyph ascent shifted up by one tile-height per row; pass
   * through {@link MenuArt#renderAscent(int)} when emitting). Empty for a non-tiled glyph.
   */
  static List<TileRow> tileRows(Glyph glyph) {
    if (glyph == null || !glyph.tiled()) {
      return List.of();
    }
    int tileScreen = glyph.height() / MenuArt.TILE_GRID;
    String stem = stripStem(glyph.texturePath());
    List<TileRow> rows = new ArrayList<>(MenuArt.TILE_GRID);
    for (int r = 0; r < MenuArt.TILE_GRID; r++) {
      char[] codepoints = new char[MenuArt.TILE_GRID];
      for (int c = 0; c < MenuArt.TILE_GRID; c++) {
        codepoints[c] = (char) (glyph.codepoint() + r * MenuArt.TILE_GRID + c);
      }
      rows.add(new TileRow(stem + ".row" + r + ".png", codepoints, glyph.ascent() - r * tileScreen));
    }
    return rows;
  }

  /**
   * The tiles of a tiled background in reading order (row-major), for the title-trick: each carries its
   * code point, on-screen left edge ({@code leftX + col*tile}) and advance ({@link MenuArt#TILE_ADVANCE}-equiv).
   * Vertical placement comes from the row provider {@link TileRow#ascent()}. Empty for a non-tiled glyph.
   */
  static List<Tile> tiles(Glyph glyph) {
    if (glyph == null || !glyph.tiled()) {
      return List.of();
    }
    int tileScreen = glyph.height() / MenuArt.TILE_GRID;
    // Real per-tile advances from the manifest (content-derived). A solid tile advances tileScreen+1
    // (Minecraft's bitmap glyph advance = displayedWidth + 1); a partial tile advances less; a fully
    // transparent tile is 0 and is SKIPPED entirely (nothing to draw, no cursor move). Falling back to
    // the uniform tileScreen+1 only if the manifest is missing (e.g. a build that never ran
    // tile-backgrounds).
    int[] advances = TILE_ADVANCES.get(stripStem(glyph.texturePath()));
    List<Tile> tiles = new ArrayList<>(MenuArt.TILE_GRID * MenuArt.TILE_GRID);
    for (int r = 0; r < MenuArt.TILE_GRID; r++) {
      for (int c = 0; c < MenuArt.TILE_GRID; c++) {
        int idx = r * MenuArt.TILE_GRID + c;
        int advance = advances != null ? advances[idx] : tileScreen + 1;
        if (advance <= 0) {
          continue; // fully-transparent tile — draw nothing
        }
        char codepoint = (char) (glyph.codepoint() + idx);
        // leftX places the tile on the on-screen grid (tiles abut); renderWidth is the EXACT MC advance
        // the cursor-neutral return must undo, so successive tiles neither drift nor gap regardless of
        // content.
        tiles.add(new Tile(codepoint, glyph.leftX() + c * tileScreen, advance));
      }
    }
    return tiles;
  }

  /** Loads {@link #TILE_ADVANCES_RESOURCE}: lines {@code <stem>=<a0>,<a1>,…} → stem → advance array. An
   *  absent/blank file yields an empty map ({@link #tiles} then falls back to a uniform advance). */
  private static Map<String, int[]> loadTileAdvances() {
    Map<String, int[]> map = new HashMap<>();
    try (InputStream in = MenuArtTiling.class.getResourceAsStream(TILE_ADVANCES_RESOURCE)) {
      if (in == null) {
        return map;
      }
      try (BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
        String line;
        while ((line = reader.readLine()) != null) {
          line = line.trim();
          if (line.isEmpty() || line.charAt(0) == '#' || line.indexOf('=') < 0) {
            continue;
          }
          int eq = line.indexOf('=');
          String stem = line.substring(0, eq).trim();
          String[] parts = line.substring(eq + 1).trim().split(",");
          int[] advances = new int[parts.length];
          for (int i = 0; i < parts.length; i++) {
            advances[i] = Integer.parseInt(parts[i].trim());
          }
          map.put(stem, advances);
        }
      }
    } catch (IOException | NumberFormatException exception) {
      throw new IllegalStateException("Failed to read " + TILE_ADVANCES_RESOURCE, exception);
    }
    return Map.copyOf(map);
  }

  /** Strip a {@code .png} suffix so {@code ui/chest/chest_6.png} → {@code ui/chest/chest_6} (tile stem). */
  private static String stripStem(String texturePath) {
    return texturePath.endsWith(".png")
        ? texturePath.substring(0, texturePath.length() - ".png".length())
        : texturePath;
  }
}
