package com.sexidium.core.lib.net;

import com.sexidium.core.Branding;
import com.sexidium.core.menu.MenuArt;
import com.sexidium.core.menu.pack.ResourcePackInfo;
import com.sexidium.core.menu.pack.SexidiumResourcePack;
import com.sexidium.core.platform.ConfigurationAdapter;
import com.sexidium.core.platform.ServerAdapter;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Hosts the generated {@link SexidiumResourcePack} over HTTP so Java clients can auto-download it on
 * join (the adapter calls {@code setResourcePack(url, sha1)}). Unlike {@link ApiServer} — which is
 * loopback-only because only the local Discord bot talks to it — this server must be reachable by the
 * <i>players'</i> machines, so it binds to a configurable public address. Admins who would rather host
 * the pack elsewhere (CDN, existing webserver) set {@code ui.resource-pack.url} and this server stays
 * off.
 *
 * <p>Config ({@code config.yml}):</p>
 * <pre>
 * ui:
 *   resource-pack:
 *     enabled: true          # master switch for the whole art layer's pack delivery
 *     url: ""                # external host override; when set, this server does NOT start
 *     host: ""               # public host/IP clients connect to (REQUIRED for remote players)
 *     bind: "0.0.0.0"        # local interface to bind
 *     port: 8788
 * </pre>
 */
public final class ResourcePackServer {
  private final ServerAdapter serverAdapter;
  private ResourcePackInfo pack;
  private HttpServer server;
  private ExecutorService executor;

  public ResourcePackServer(ServerAdapter serverAdapter) {
    this.serverAdapter = serverAdapter;
  }

  /** The built pack + its resolved download URL, or {@code null} when delivery is disabled/unavailable. */
  public ResourcePackInfo pack() {
    return pack;
  }

  /**
   * Builds the pack, resolves its download URL, and starts the HTTP host (unless an external URL is
   * configured). Safe to call once at startup; failures degrade to "no pack" (Java clients keep the
   * plain chest menus). Returns the pack info, or {@code null} if disabled/failed.
   */
  public ResourcePackInfo start() {
    ConfigurationAdapter configuration = serverAdapter.configuration();
    if (!configuration.getBoolean("ui.resource-pack.enabled", false)) {
      serverAdapter.logger().info("Menu resource pack disabled in config; Java clients use plain chest menus.");
      return null;
    }
    // Global in-client art nudge (absorbs a client/version baseline mismatch). Applied BEFORE the build so
    // dy lands in the pack font ascent (and changes the SHA so clients re-download) and dx in the runtime
    // title shift. The measured baseline correction is baked in MenuArt.DEFAULT_CALIBRATE_*; the config
    // values are ADDED on top (0 = use the baseline). Read here so a config edit + restart re-tunes with
    // no recompile.
    int calibrateDx = MenuArt.DEFAULT_CALIBRATE_DX + configuration.getInt("ui.menu-art.calibrate-dx", 0);
    int calibrateDy = MenuArt.DEFAULT_CALIBRATE_DY + configuration.getInt("ui.menu-art.calibrate-dy", 0);
    MenuArt.setCalibration(calibrateDx, calibrateDy);
    serverAdapter.logger().info("Menu art calibration: dx=" + MenuArt.calibrateDx()
        + " dy=" + MenuArt.calibrateDy() + " (GUI px; baseline " + MenuArt.DEFAULT_CALIBRATE_DX
        + "/" + MenuArt.DEFAULT_CALIBRATE_DY + " + config).");
    ResourcePackInfo built;
    try {
      built = SexidiumResourcePack.build(Branding.label(configuration), bundledTextures());
    } catch (RuntimeException exception) {
      serverAdapter.logger().warning("Could not build the menu resource pack; custom art disabled.", exception);
      return null;
    }

    String externalUrl = configuration.getString("ui.resource-pack.url", "");
    if (externalUrl != null && !externalUrl.isBlank()) {
      // Admin hosts the pack themselves. The client verifies the download against the SHA-1 we hand it,
      // so it MUST be the hash of the file actually served from that URL — not our generated bytes,
      // which the admin's real-art file will not match. Prefer an explicitly configured sha1; if none
      // is given, fall back to the generated hash and warn that the hosted file must be byte-identical.
      String configuredSha = normalizeSha(configuration.getString("ui.resource-pack.sha1", ""));
      String sha = configuredSha != null ? configuredSha : built.sha1Hex();
      if (configuredSha == null) {
        serverAdapter.logger().warning("ui.resource-pack.url is set but ui.resource-pack.sha1 is not — "
            + "advertising the generated pack's hash. The file you host at " + externalUrl.trim()
            + " MUST be byte-identical to the generated pack, or every client will reject it. Set "
            + "ui.resource-pack.sha1 to your hosted file's SHA-1 to host custom art.");
      }
      pack = new ResourcePackInfo(built.bytes(), sha, externalUrl.trim());
      serverAdapter.logger().info("Menu resource pack served externally from " + pack.url()
          + " (sha1 " + pack.sha1Hex() + ").");
      return pack;
    }

    String bind = configuration.getString("ui.resource-pack.bind", "0.0.0.0");
    int port = configuration.getInt("ui.resource-pack.port", 8788);
    if (port < 0 || port > 65535) {
      serverAdapter.logger().warning("ui.resource-pack.port " + port
          + " is out of range (0-65535); custom art disabled.");
      return null;
    }
    String host = configuration.getString("ui.resource-pack.host", "");
    if (host == null || host.isBlank()) {
      host = "0.0.0.0".equals(bind) ? "127.0.0.1" : bind;
      serverAdapter.logger().warning("ui.resource-pack.host is unset; advertising " + host
          + " — set it to your server's public address so remote players can download the menu pack.");
    }
    try {
      server = HttpServer.create(new InetSocketAddress(bind, port), 0);
      byte[] bytes = built.bytes();
      server.createContext("/sexidium.zip", exchange -> serve(exchange, bytes));
      executor = Executors.newSingleThreadExecutor(runnable -> {
        Thread thread = new Thread(runnable, "Sexidium-Pack");
        thread.setDaemon(true);
        return thread;
      });
      server.setExecutor(executor);
      server.start();
      pack = built.withUrl("http://" + host + ":" + port + "/sexidium.zip");
      serverAdapter.logger().info("Menu resource pack hosted at " + pack.url() + " (sha1 " + pack.sha1Hex() + ").");
      return pack;
    } catch (IOException | RuntimeException exception) {
      // Any host failure (bind in use, bad bind address, unresolved host) degrades to "no pack" — it
      // must never crash plugin enable. Java clients then keep the plain chest menus.
      serverAdapter.logger().warning("Failed to host the menu resource pack on " + bind + ":" + port
          + "; custom art disabled.", exception);
      stop();
      return null;
    }
  }

  /**
   * A {@link SexidiumResourcePack.TextureSource} backed by textures bundled into the jar under
   * {@code bundled/menupack-textures/} (staged at build time from {@code assets/} via
   * {@code -PmenuPackZip}). When present the pack ships real GUI art; when absent every path returns
   * {@code null} and the generator uses placeholders. The staged {@code manifest.txt} lists every
   * bundled texture path, so {@link SexidiumResourcePack.TextureSource#texturePaths()} can ship the
   * full {@code ./icons/} set (referenced icons get a model; the rest ship as bare textures). Logged
   * once so an operator sees which is active.
   */
  private SexidiumResourcePack.TextureSource bundledTextures() {
    boolean real = serverAdapter.resources()
        .openResource("bundled/menupack-textures/" + MenuArt.glyphs().get(0).texturePath()).isPresent();
    serverAdapter.logger().info(real
        ? "Menu pack: using bundled custom textures (from -PmenuPackZip)."
        : "Menu pack: no bundled textures found; using generated placeholder art.");
    List<String> manifest = bundledManifest();
    return new SexidiumResourcePack.TextureSource() {
      @Override
      public byte[] texture(String packTexturePath) {
        try (InputStream stream = serverAdapter.resources()
            .openResource("bundled/menupack-textures/" + packTexturePath).orElse(null)) {
          return stream == null ? null : stream.readAllBytes();
        } catch (IOException exception) {
          return null;
        }
      }

      @Override
      public Collection<String> texturePaths() {
        return manifest;
      }
    };
  }

  /** Every bundled texture path from the staged {@code manifest.txt}, or empty if none was staged. */
  private List<String> bundledManifest() {
    try (InputStream stream = serverAdapter.resources()
        .openResource("bundled/menupack-textures/manifest.txt").orElse(null)) {
      if (stream == null) {
        return List.of();
      }
      List<String> paths = new ArrayList<>();
      for (String line : new String(stream.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
        String path = line.trim();
        if (!path.isEmpty()) {
          paths.add(path);
        }
      }
      return paths;
    } catch (IOException exception) {
      return List.of();
    }
  }

  /** A configured external SHA-1 normalised to 40 lowercase hex chars, or {@code null} if blank/invalid. */
  private String normalizeSha(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }
    String hex = value.trim().toLowerCase(java.util.Locale.ROOT);
    if (hex.length() != 40 || !hex.chars().allMatch(c -> (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'))) {
      serverAdapter.logger().warning("ui.resource-pack.sha1 is not a 40-char hex SHA-1; ignoring it.");
      return null;
    }
    return hex;
  }

  public void stop() {
    if (server != null) {
      server.stop(0);
      server = null;
    }
    if (executor != null) {
      executor.shutdownNow();
      executor = null;
    }
  }

  private void serve(HttpExchange exchange, byte[] bytes) throws IOException {
    if (!"GET".equalsIgnoreCase(exchange.getRequestMethod()) && !"HEAD".equalsIgnoreCase(exchange.getRequestMethod())) {
      exchange.sendResponseHeaders(405, -1);
      exchange.close();
      return;
    }
    exchange.getResponseHeaders().add("Content-Type", "application/zip");
    if ("HEAD".equalsIgnoreCase(exchange.getRequestMethod())) {
      exchange.sendResponseHeaders(200, -1);
      exchange.close();
      return;
    }
    exchange.sendResponseHeaders(200, bytes.length);
    try (OutputStream outputStream = exchange.getResponseBody()) {
      outputStream.write(bytes);
    }
  }
}
