plugins {
  `java-library`
  jacoco
}

dependencies {
  compileOnly("org.xerial:sqlite-jdbc:3.53.1.0")
  testImplementation("org.xerial:sqlite-jdbc:3.53.1.0")
  testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
  toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

// Embed an optional lobby world/settings bundle (generated by the root prepareLobbyBundle task).
// It lands in core's resources, so every adapter jar — which copies core's main output — ships it.
// The menu-art textures (prepareMenuPack, from -PmenuPackZip) land the same way under
// bundled/menupack-textures, and SexidiumResourcePack uses them in place of placeholder art.
sourceSets.main {
  resources.srcDir(rootProject.layout.buildDirectory.dir("generated/lobby-bundle"))
  resources.srcDir(rootProject.layout.buildDirectory.dir("generated/menu-pack"))
  // Bundled TNT War map worlds (prepareMapBundle, from assets/worlds/tntwars); land under
  // bundled/maps/<world-path>.zip + a manifest, which MapBundle auto-extracts into the world root.
  resources.srcDir(rootProject.layout.buildDirectory.dir("generated/map-bundle"))
  // build-info.properties: the version half of this node's published build identity. See BuildIdentity.
  resources.srcDir(rootProject.layout.buildDirectory.dir("generated/buildinfo"))
}

// An embedded bundle is simply shipped in the jar; the runtime seeds the lobby from it when the world
// does not yet exist (worlds.lobby.create-if-missing) and serves the menu pack with any bundled
// textures. No config flag is flipped at build time.
tasks.processResources {
  dependsOn(rootProject.tasks.named("prepareLobbyBundle"))
  dependsOn(rootProject.tasks.named("prepareMenuPack"))
  dependsOn(rootProject.tasks.named("prepareMapBundle"))
  dependsOn(rootProject.tasks.named("generateBuildInfo"))
}

tasks.jar {
  archiveBaseName.set("Sexidium-Core")
}

tasks.test {
  useJUnitPlatform()
  finalizedBy(tasks.named("jacocoTestReport"))
}

tasks.named<JacocoReport>("jacocoTestReport") {
  reports { xml.required.set(true) }
}

// Re-bake the per-screen menu backgrounds (assets/ui/screens/<id>.png) from SceneTemplates + committed
// art, at the <=256px font-atlas ceiling. Run after editing the scene templates or the Components palette:
//   ./gradlew :packages:core:bakeMenuScreens
val bakeMenuScreens by tasks.registering(JavaExec::class) {
  group = "sexidium"
  description = "Re-bake assets/ui/screens/*.png from SceneTemplates at <=256px."
  dependsOn(tasks.named("classes"))
  mainClass.set("com.sexidium.core.menu.scene.bake.SceneBaker")
  classpath = sourceSets["main"].runtimeClasspath
  args("pack", "assets", "UI/frame")
  workingDir = rootProject.projectDir
}
